/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.codegen.tables.Bucket;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BucketRecord extends UpdatableRecordImpl<BucketRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>BUCKET.UUID</code>.
     */
    public void setUuid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>BUCKET.UUID</code>.
     */
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>BUCKET.OWNER</code>.
     */
    public void setOwner(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>BUCKET.OWNER</code>.
     */
    public String getOwner() {
        return (String) get(1);
    }

    /**
     * Setter for <code>BUCKET.NAME</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>BUCKET.NAME</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>BUCKET.SHARE</code>.
     */
    public void setShare(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>BUCKET.SHARE</code>.
     */
    public Double getShare() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>BUCKET.CREATED</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>BUCKET.CREATED</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>BUCKET.UPDATED</code>.
     */
    public void setUpdated(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>BUCKET.UPDATED</code>.
     */
    public LocalDateTime getUpdated() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BucketRecord
     */
    public BucketRecord() {
        super(Bucket.BUCKET);
    }

    /**
     * Create a detached, initialised BucketRecord
     */
    public BucketRecord(String uuid, String owner, String name, Double share, LocalDateTime created, LocalDateTime updated) {
        super(Bucket.BUCKET);

        setUuid(uuid);
        setOwner(owner);
        setName(name);
        setShare(share);
        setCreated(created);
        setUpdated(updated);
        resetChangedOnNotNull();
    }
}
