/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.codegen.tables.Income;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IncomeRecord extends UpdatableRecordImpl<IncomeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>income.uuid</code>.
     */
    public void setUuid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>income.uuid</code>.
     */
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>income.owner</code>.
     */
    public void setOwner(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>income.owner</code>.
     */
    public String getOwner() {
        return (String) get(1);
    }

    /**
     * Setter for <code>income.amount</code>.
     */
    public void setAmount(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>income.amount</code>.
     */
    public Integer getAmount() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>income.occurred</code>.
     */
    public void setOccurred(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>income.occurred</code>.
     */
    public LocalDateTime getOccurred() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>income.category</code>.
     */
    public void setCategory(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>income.category</code>.
     */
    public String getCategory() {
        return (String) get(4);
    }

    /**
     * Setter for <code>income.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>income.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>income.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>income.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>income.updated</code>.
     */
    public void setUpdated(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>income.updated</code>.
     */
    public LocalDateTime getUpdated() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IncomeRecord
     */
    public IncomeRecord() {
        super(Income.INCOME);
    }

    /**
     * Create a detached, initialised IncomeRecord
     */
    public IncomeRecord(String uuid, String owner, Integer amount, LocalDateTime occurred, String category, String description, LocalDateTime created, LocalDateTime updated) {
        super(Income.INCOME);

        setUuid(uuid);
        setOwner(owner);
        setAmount(amount);
        setOccurred(occurred);
        setCategory(category);
        setDescription(description);
        setCreated(created);
        setUpdated(updated);
        resetChangedOnNotNull();
    }
}
