/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen;


import org.jooq.codegen.tables.Account;
import org.jooq.codegen.tables.Bucket;
import org.jooq.codegen.tables.Expense;
import org.jooq.codegen.tables.Income;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ACCOUNT</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>BUCKET</code>.
     */
    public static final Bucket BUCKET = Bucket.BUCKET;

    /**
     * The table <code>EXPENSE</code>.
     */
    public static final Expense EXPENSE = Expense.EXPENSE;

    /**
     * The table <code>INCOME</code>.
     */
    public static final Income INCOME = Income.INCOME;
}
