/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen;


import org.jooq.codegen.tables.Account;
import org.jooq.codegen.tables.Expense;
import org.jooq.codegen.tables.Income;
import org.jooq.codegen.tables.Partition;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>expense</code>.
     */
    public static final Expense EXPENSE = Expense.EXPENSE;

    /**
     * The table <code>income</code>.
     */
    public static final Income INCOME = Income.INCOME;

    /**
     * The table <code>partition</code>.
     */
    public static final Partition PARTITION = Partition.PARTITION;
}
