/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.codegen.DefaultSchema;
import org.jooq.codegen.Keys;
import org.jooq.codegen.tables.Account.AccountPath;
import org.jooq.codegen.tables.Partition.PartitionPath;
import org.jooq.codegen.tables.records.ExpenseRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Expense extends TableImpl<ExpenseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>expense</code>
     */
    public static final Expense EXPENSE = new Expense();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExpenseRecord> getRecordType() {
        return ExpenseRecord.class;
    }

    /**
     * The column <code>expense.uuid</code>.
     */
    public final TableField<ExpenseRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>expense.owner</code>.
     */
    public final TableField<ExpenseRecord, String> OWNER = createField(DSL.name("owner"), SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>expense.amount</code>.
     */
    public final TableField<ExpenseRecord, Integer> AMOUNT = createField(DSL.name("amount"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>expense.occurred</code>.
     */
    public final TableField<ExpenseRecord, LocalDateTime> OCCURRED = createField(DSL.name("occurred"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>expense.category</code>.
     */
    public final TableField<ExpenseRecord, String> CATEGORY = createField(DSL.name("category"), SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>expense.description</code>.
     */
    public final TableField<ExpenseRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>expense.partition</code>.
     */
    public final TableField<ExpenseRecord, String> PARTITION = createField(DSL.name("partition"), SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>expense.created</code>.
     */
    public final TableField<ExpenseRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>expense.updated</code>.
     */
    public final TableField<ExpenseRecord, LocalDateTime> UPDATED = createField(DSL.name("updated"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    private Expense(Name alias, Table<ExpenseRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Expense(Name alias, Table<ExpenseRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>expense</code> table reference
     */
    public Expense(String alias) {
        this(DSL.name(alias), EXPENSE);
    }

    /**
     * Create an aliased <code>expense</code> table reference
     */
    public Expense(Name alias) {
        this(alias, EXPENSE);
    }

    /**
     * Create a <code>expense</code> table reference
     */
    public Expense() {
        this(DSL.name("expense"), null);
    }

    public <O extends Record> Expense(Table<O> path, ForeignKey<O, ExpenseRecord> childPath, InverseForeignKey<O, ExpenseRecord> parentPath) {
        super(path, childPath, parentPath, EXPENSE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ExpensePath extends Expense implements Path<ExpenseRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ExpensePath(Table<O> path, ForeignKey<O, ExpenseRecord> childPath, InverseForeignKey<O, ExpenseRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ExpensePath(Name alias, Table<ExpenseRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ExpensePath as(String alias) {
            return new ExpensePath(DSL.name(alias), this);
        }

        @Override
        public ExpensePath as(Name alias) {
            return new ExpensePath(alias, this);
        }

        @Override
        public ExpensePath as(Table<?> alias) {
            return new ExpensePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ExpenseRecord> getPrimaryKey() {
        return Keys.EXPENSE__PK_EXPENSE;
    }

    @Override
    public List<ForeignKey<ExpenseRecord, ?>> getReferences() {
        return Arrays.asList(Keys.EXPENSE__FK_EXPENSE_PK_ACCOUNT, Keys.EXPENSE__FK_EXPENSE_PK_PARTITION);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.EXPENSE__FK_EXPENSE_PK_ACCOUNT, null);

        return _account;
    }

    private transient PartitionPath _partition;

    /**
     * Get the implicit join path to the <code>partition</code> table.
     */
    public PartitionPath partition() {
        if (_partition == null)
            _partition = new PartitionPath(this, Keys.EXPENSE__FK_EXPENSE_PK_PARTITION, null);

        return _partition;
    }

    @Override
    public Expense as(String alias) {
        return new Expense(DSL.name(alias), this);
    }

    @Override
    public Expense as(Name alias) {
        return new Expense(alias, this);
    }

    @Override
    public Expense as(Table<?> alias) {
        return new Expense(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Expense rename(String name) {
        return new Expense(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Expense rename(Name name) {
        return new Expense(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Expense rename(Table<?> name) {
        return new Expense(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Expense where(Condition condition) {
        return new Expense(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Expense where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Expense where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Expense where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Expense where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Expense where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Expense where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Expense where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Expense whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Expense whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
