CREATE TABLE if NOT EXISTS ACCOUNT (
    UUID VARCHAR(1000),
    ROLES VARCHAR(1000),
    HASH VARCHAR(1000),
    SALT VARCHAR(1000),
    CREATED TIMESTAMP NOT NULL,
    UPDATED TIMESTAMP NOT NULL,
    PRIMARY KEY (uuid)
);

CREATE TABLE if NOT EXISTS BUCKET (
    UUID VARCHAR(1000),
    OWNER VARCHAR(1000),
    NAME VARCHAR(1000),
    SHARE DOUBLE,
    CREATED TIMESTAMP NOT NULL,
    UPDATED TIMESTAMP NOT NULL,
    PRIMARY KEY (UUID),
    FOREIGN KEY (OWNER) REFERENCES ACCOUNT (UUID)
);

CREATE TABLE if NOT EXISTS INCOME (
    UUID VARCHAR(1000),
    OWNER VARCHAR(1000),
    AMOUNT INTEGER,
    OCCURRED TIMESTAMP NOT NULL,
    CATEGORY VARCHAR(1000),
    DESCRIPTION VARCHAR(1000),
    CREATED TIMESTAMP NOT NULL,
    UPDATED TIMESTAMP NOT NULL,
    PRIMARY KEY (UUID),
    FOREIGN KEY (OWNER) REFERENCES ACCOUNT (UUID)
);

CREATE TABLE if NOT EXISTS EXPENSE (
    UUID VARCHAR(1000),
    OWNER VARCHAR(1000),
    AMOUNT INTEGER,
    OCCURRED TIMESTAMP NOT NULL,
    CATEGORY VARCHAR(1000),
    DESCRIPTION VARCHAR(1000),
    BUCKET VARCHAR(1000),
    CREATED TIMESTAMP NOT NULL,
    UPDATED TIMESTAMP NOT NULL,
    PRIMARY KEY (UUID),
    FOREIGN KEY (OWNER) REFERENCES ACCOUNT (UUID),
    FOREIGN KEY (BUCKET) REFERENCES BUCKET (UUID)
);

